name: build NextJS app

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        uses: borales/actions-yarn@v5
        with:
          cmd: install # will run `yarn install` command
      - name: Build
        uses: borales/actions-yarn@v5
        with:
          cmd: build
        env:
          GHOST_URL: https://cms.vigue.me
          GHOST_ADMIN_KEY: ${{ secrets.GHOST_ADMIN_KEY }}
          GHOST_CONTENT_KEY: ${{ secrets.GHOST_CONTENT_KEY }}
          GHOST_WEBHOOK_KEY: 1234test_not_valid
          GHOST_PATH: ghost
          IMGPROXY_URL: https://cdn.vigue.me
          IMGPROXY_KEY: 1234abcd
          IMGPROXY_SALT: 1234abcd
